export const data = [
  {
    imgSrc: "https://m.media-amazon.com/images/I/71N0+IGOsLL._AC_UY218_.jpg",
    title: "HP Chromebook 14 Intel Celeron N4020-4GB SDRAM",
    price: 23490,
    rating: 5,
    ram: "32GB",
    brand: "HP",
    cpu: "Intel Core i5",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/819rZe+EVjL._AC_UY218_.jpg",
    title: "HP 14s-Intel Celeron N4500",
    price: 26490,
    rating: 5,
    ram: "8GB",
    brand: "HP",
    cpu: "AMD Ryzen 3",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/81bYnMz1BbL._AC_UY218_.jpg",
    title: "HP 14 (2021) Thin & Light Intel Celeron N4500 Laptop with Alexa Built-in",
    price: 21490,
    rating: 5,
    ram: "16GB",
    brand: "HP",
    cpu: "Intel Core i5",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/61IvGo6OKyL._AC_UY218_.jpg",
    title: "HP Chromebook 14 Intel Celeron N4020-4GB SDRAM",
    price: 23790,
    rating: 5,
    ram: "32GB",
    brand: "DELL",
    cpu: "Intel Core i7",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/51HotqEitRL._AC_UY218_.jpg",
    title: "DELL 14s-Intel Celeron N4500",
    price: 43490,
    rating: 5,
    ram: "8GB",
    brand: "DELL",
    cpu: "Intel Core i5",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/61-+DDxcdxL._AC_UY218_.jpg",
    title: "DELL 14 (2021) Thin & Light Intel Celeron N4500 Laptop with Alexa Built-in",
    price: 53490,
    rating: 5,
    ram: "16GB",
    brand: "DELL",
    cpu: "AMD Ryzen 3",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/612whSmr1ML._AC_UY218_.jpg",
    title: "Dell New Inspiron 3511 Laptop Intel i3-1115G4",
    price: 19490,
    rating: 5,
    ram: "32GB",
    brand: "DELL",
    cpu: "Intel Core i7",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/619wdC9vcCL._AC_UY218_.jpg",
    title: "LENOVO 14s-Intel Celeron N4500",
    price: 45490,
    rating: 5,
    ram: "8GB",
    brand: "LENOVO",
    cpu: "AMD Ryzen 5",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/61q6x-ll5FL._AC_UY218_.jpg",
    title: "LENOVO 14 (2021) Thin & Light Intel Celeron N4500 Laptop with Alexa Built-in",
    price: 63490,
    rating: 5,
    ram: "16GB",
    brand: "LENOVO",
    cpu: "Intel Core i5",
  },
  {
    imgSrc: "https://m.media-amazon.com/images/I/61s7sJEpsVL._AC_UY218_.jpg",
    title: "LENOVO New Inspiron 3511 Laptop Intel i3-1115G4",
    price: 9490,
    rating: 5,
    ram: "32GB",
    brand: "LENOVO",
    cpu: "AMD Ryzen 5",
  },
];
